server:
  port: 8080
spring:
  application:
    name: "bancoVoip"
  devtools:
    add-properties: false
  datasource:
    url: "jdbc:postgresql://localhost:5432/postgres"
    username: "postgres"
    password: "root"
    driverClassName: "org.postgresql.Driver"
    driver-class-name: "org.postgresql.Driver"
  profiles:
    include: null
  jpa:
    databasePlatform: "org.hibernate.dialect.PostgreSQLDialect"
management:
  endpoints:
    web:
      exposure:
        include: "health,prometheus"
  endpoint:
    health:
      probes:
        enabled: true
cors:
  allowed-origins: "http://localhost:4200,http://localhost:8080, http://192.168.1.2"
